source 'https://rubygems.org'

gem 'unicorn'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'sprockets'
gem 'sprockets-helpers', require: 'sinatra/sprockets-helpers'
gem 'slim'
gem 'coffee-script'
gem 'uglifier'
gem 'sass'
gem 'bootstrap-sass'
