source 'https://rubygems.org'

gem 'unicorn'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'therubyracer'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'slim'
gem 'coffee-script'
gem 'uglifier'
gem 'sass'
gem 'bootstrap-sass'
gem 'less'
